version: '3.1'

services:
 
  jwt-auth:
    image: node:18.13-alpine3.17
    working_dir: /data
    depends_on:
     - mongo
     - mongo-express
    ports:
     - 4001:4001
    volumes:
     - ./:/data
    environment:
     - NODE_ENV=local
    command: npm start

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
